export const gamesData = [
  {
    developer: 'Ubisoft',
    platform: 'ps4',
    title: 'Watch Dogs 2 - PS4',
    old_price: 'R$ 259,90',
    new_price: 'R$ 199,90',
    payment_conditions: 'em até 3x de R$ 48,90 sem juros',
    poster: '/assets/img/watch_dogs_2.png',
    tag_title: '25% off',
    tag_type: 'discount'
  },
  {
    developer: 'Crystal Dynamics',
    title: 'Rise of Tomb Raider - Xbox One',
    platform: 'xbox_one',
    old_price: 'R$ 259,90',
    new_price: 'R$ 199,90',
    payment_conditions: 'em até 3x de R$ 48,90 sem juros',
    poster: '/assets/img/rise_of_tomb_raider.png',
    tag_title: 'Novidade',
    tag_type: 'news'
  },
  {
    developer: 'Rocksteady Studios',
    title: 'Batman: Arkham Knight - PS4',
    platform: 'ps4',
    old_price: 'R$ 259,90',
    new_price: 'R$ 199,90',
    payment_conditions: 'em até 3x de R$ 48,90 sem juros',
    poster: '/assets/img/batman_arkham_knight.png',
    tag_title: 'Últimas Unidades',
    tag_type: 'lastUnits',
  },
  {
    developer: 'Ubisoft',
    title: "Assassin's Creed Origins - PC",
    platform: 'pc_windows',
    old_price: 'R$ 259,90',
    new_price: 'R$ 199,90',
    payment_conditions: 'em até 3x de R$ 48,90 sem juros',
    poster: '/assets/img/assassins_creed_origins.png',
    tag_title: 'Em breve',
    tag_type: 'comingSoon',
  },
  {
    developer: 'Naughty Dog',
    title: "Uncharted 4 - A Thief's End - PC",
    platform: 'pc_mac',
    old_price: 'R$ 259,90',
    new_price: 'R$ 199,90',
    payment_conditions: 'em até 3x de R$ 48,90 sem juros',
    poster: '/assets/img/uncharted_4.png',
    tag_title: 'Destaque',
    tag_type: 'emphasis',
  },
  {
    developer: 'FromSoftware',
    title: 'Bloodborne - PS4',
    platform: 'ps4',
    old_price: 'R$ 259,90',
    new_price: 'R$ 199,90',
    payment_conditions: 'em até 3x de R$ 48,90 sem juros',
    poster: '/assets/img/bloodborne.png',
    tag_title: '25% off',
    tag_type: 'discount',
  },
  {
    developer: ' Ninja Theory',
    title: "Hellblade: Senua's Sacrifice - PC",
    platform: 'pc_windows',
    old_price: 'R$ 259,90',
    new_price: 'R$ 199,90',
    payment_conditions: 'em até 3x de R$ 48,90 sem juros',
    poster: '/assets/img/hellblade.png',
    tag_title: 'Novidade',
    tag_type: 'news'
  },
  {
    developer: 'Insomniac Games',
    title: "Marvel's Spider-Man - PS4",
    platform: 'ps4',
    old_price: 'R$ 259,90',
    new_price: 'R$ 199,90',
    payment_conditions: 'em até 3x de R$ 48,90 sem juros',
    poster: '/assets/img/marvel_spider_man.png',
    tag_title: 'Últimas Unidades',
    tag_type: 'lastUnits',
  }
]